name: "🐛 Bug Report"
description: Report a reproducible bug or regression in the library.
labels: [bug]
body:
  - type: markdown
    attributes:
      value: |
        # 🐛 Bug Report

        Please fill out all required sections to help us fix the issue faster.

  - type: checkboxes
    attributes:
      label: Checklist
      description: Confirm the following before submitting:
      options:
        - label: I tested the latest version.
          required: true
        - label: I’m using a supported React Native version.
          required: true
        - label: I searched existing issues.
          required: true

  - type: textarea
    id: summary
    attributes:
      label: Bug Summary
      description: A clear and concise description of the bug.
    validations:
      required: true

  - type: input
    id: version
    attributes:
      label: Package Version
      placeholder: e.g., 1.0.2
    validations:
      required: true

  - type: textarea
    id: environment
    attributes:
      label: Environment Info
      description: Paste output from `npx react-native info`
      render: shell
      value: |
        ```sh
        npx react-native info
        ```
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      description: Provide steps to reproduce the issue.
      placeholder: |
        1. Install the package
        2. Import a component
        3. Run the app
        4. Observe the issue
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What should happen instead?
    validations:
      required: true

  - type: input
    id: repro
    attributes:
      label: Reproducible Example
      placeholder: e.g., https://github.com/user/repro-app
    validations:
      required: true

  - type: textarea
    id: context
    attributes:
      label: Additional Context
      description: Logs, device info, screenshots, or anything relevant.
