blank_issues_enabled: true
contact_links:
  - name: ✨ Feature Request
    url: https://github.com/gaureshpai/reactnativeepictrailsds/discussions/new?category=ideas
    about: Suggest new features in the Ideas discussion category.

  - name: 💬 General Discussion & Help
    url: https://github.com/gaureshpai/reactnativeepictrailsds/discussions
    about: Ask questions or start general discussions here.